#!/usr/bin/env python3
"""Merge researched names and descriptions into resources/data/names.json.

Input: JSON files shaped like the docs/i18n names/effects requests, with each
entry carrying {"ko", ["ja"], "confidence", "source", "note"}. Sections:
items, moves, abilities, versions, item-effects, move-effects, ability-effects.

Only "verified" / "single" entries with Korean text are merged; existing
dictionary values win unless --overwrite. A review list is written to
docs/i18n/review-names.md.

Usage: scripts/i18n/merge_names.py [--overwrite] <file.json> [...]
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DICTIONARY = ROOT / "resources/data/names.json"
REVIEW = ROOT / "docs/i18n/review-names.md"
SECTIONS = ("items", "moves", "abilities", "versions",
            "item-effects", "move-effects", "ability-effects")


def main(argv):
    overwrite = "--overwrite" in argv
    files = [Path(a) for a in argv if not a.startswith("--")]
    if not files:
        print(__doc__)
        return 2
    dictionary = json.loads(DICTIONARY.read_text(encoding="utf-8"))
    merged, skipped, single = 0, [], []
    for path in files:
        data = json.loads(path.read_text(encoding="utf-8"))
        for section in SECTIONS:
            target = dictionary.setdefault(section, {})
            for identifier, entry in data.get(section, {}).items():
                ko = " ".join((entry.get("ko") or "").split())
                ja = (entry.get("ja") or "").strip()
                confidence = entry.get("confidence", "uncertain")
                if not ko or confidence not in ("verified", "single"):
                    skipped.append((section, identifier, entry.get("note", "")))
                    continue
                if identifier in target and not overwrite:
                    continue
                target[identifier] = {"ko": ko, "ja": ja} if ja else ko
                merged += 1
                if confidence == "single":
                    single.append((section, identifier, ko, entry.get("source", "")))
    for section in SECTIONS:
        dictionary[section] = dict(sorted(dictionary.get(section, {}).items()))
    DICTIONARY.write_text(json.dumps(dictionary, ensure_ascii=False, indent=2) + "\n",
                          encoding="utf-8")
    lines = ["# Name and description review", "",
             "Generated by scripts/i18n/merge_names.py.", "",
             "## Not merged (uncertain or empty)", "", "| section | identifier | note |",
             "|---|---|---|"]
    lines += [f"| {s} | {i} | {n} |" for s, i, n in sorted(skipped)]
    lines += ["", "## Merged from a single source", "", "| section | identifier | Korean | source |",
              "|---|---|---|---|"]
    lines += [f"| {s} | {i} | {k} | {src} |" for s, i, k, src in sorted(single)]
    REVIEW.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"merged {merged}, single-source {len(single)}, not merged {len(skipped)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
