#!/usr/bin/env python3
"""Merge researched place names into resources/data/place-names.json.

Input: one or more JSON files shaped like
    {"<pokeapi-location-identifier>": {"ko": "...", "ja": "...",
                                       "confidence": "verified|single|uncertain",
                                       "source": "...", "note": "..."}}

Rules:
- Only identifiers that exist in docs/i18n/location-ids.json are accepted.
- "verified" and "single" entries with a non-empty Korean name are merged.
  "uncertain" or empty ones are reported, never merged.
- Existing dictionary values win; the script only fills missing entries
  (pass --overwrite to replace them).
- A review list (uncertain, unknown identifiers, single-source) is written
  to docs/i18n/review-places.md.

Usage: scripts/i18n/merge_places.py [--overwrite] <file.json> [...]
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DICTIONARY = ROOT / "resources/data/place-names.json"
LOCATIONS = ROOT / "docs/i18n/location-ids.json"
REVIEW = ROOT / "docs/i18n/review-places.md"


def main(argv):
    overwrite = "--overwrite" in argv
    files = [Path(a) for a in argv if not a.startswith("--")]
    if not files:
        print(__doc__)
        return 2

    known = json.loads(LOCATIONS.read_text(encoding="utf-8"))
    dictionary = json.loads(DICTIONARY.read_text(encoding="utf-8"))
    places = dictionary.setdefault("places", {})

    merged, kept, single, uncertain, unknown = [], [], [], [], []
    for path in files:
        data = json.loads(path.read_text(encoding="utf-8"))
        for identifier, entry in data.items():
            if identifier.startswith("_"):
                continue
            if identifier not in known:
                unknown.append((identifier, path.name))
                continue
            # PokéAPI pseudo-locations (roaming / unknown-*) have no in-game name;
            # never merge a label someone made up for them.
            if identifier.startswith(("roaming-", "unknown-")):
                uncertain.append((identifier, known[identifier]["en"], "pseudo-location", ""))
                continue
            ko = (entry.get("ko") or "").strip()
            ja = (entry.get("ja") or "").strip()
            confidence = entry.get("confidence", "uncertain")
            if not ko or confidence not in ("verified", "single"):
                uncertain.append((identifier, known[identifier]["en"], entry.get("note", ""), ko))
                continue
            if identifier in places and not overwrite:
                kept.append(identifier)
                continue
            places[identifier] = {"ko": ko, "ja": ja} if ja else ko
            merged.append(identifier)
            if confidence == "single":
                single.append((identifier, known[identifier]["en"], ko, entry.get("source", "")))

    dictionary["places"] = dict(sorted(places.items()))
    DICTIONARY.write_text(json.dumps(dictionary, ensure_ascii=False, indent=2) + "\n",
                          encoding="utf-8")

    lines = ["# Place name review", "",
             "Generated by scripts/i18n/merge_places.py. Not merged: uncertain or empty.",
             "Merged but single-source: worth a spot check.", ""]
    lines += ["## Not merged (uncertain or empty)", "", "| identifier | English | note | guess |",
              "|---|---|---|---|"]
    lines += [f"| {i} | {en} | {note} | {ko} |" for i, en, note, ko in sorted(uncertain)]
    lines += ["", "## Merged from a single source", "", "| identifier | English | Korean | source |",
              "|---|---|---|---|"]
    lines += [f"| {i} | {en} | {ko} | {src} |" for i, en, ko, src in sorted(single)]
    if unknown:
        lines += ["", "## Unknown identifiers (ignored)", ""]
        lines += [f"- {i} ({f})" for i, f in sorted(unknown)]
    REVIEW.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"merged {len(merged)}, kept existing {len(kept)}, single-source {len(single)}, "
          f"not merged {len(uncertain)}, unknown {len(unknown)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
